# This requires Vault and https://github.com/external-secrets/kubernetes-external-secrets
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gitserver-ssh
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: gitserver
spec:
  backendType: vault
  vaultRole: sourcegraph
  data:
    - name: id_rsa
      key: kv/data/mgmt/sourcegraph/github_ssh
    # Should probably be generated via `ssh-keyscan github.com > known_hosts`
    - name: known_hosts
      key: kv/data/mgmt/sourcegraph/github_ssh
