apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-sourcegraph
bases:
  - ../namespaced
resources:
  - base/sourcegraph.StorageClass.yaml
  - base/sourcegraph.NetworkPolicy.yaml
  - gitserver/gitserver.ExternalSecret.yaml
  - frontend/sourcegraph-frontend.ExternalSecret.yaml
  - certmanager/certmanager.Issuer.yaml
patchesStrategicMerge:
  - frontend/sourcegraph-frontend.Ingress.yaml
  - gitserver/gitserver.StatefulSet.yaml
