apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sourcegraph-frontend
  annotations:
    cert-manager.io/issuer: sourcegraph-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - sourcegraph.rtr.cloud
      secretName: sourcegraph.rtr.cloud-cert

