# This requires Vault and https://github.com/external-secrets/kubernetes-external-secrets
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: load-balancer-source-ranges
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
spec:
  backendType: vault
  vaultRole: sourcegraph
  data:
    - name: load-balancer-source-ranges
      key: kv/data/mgmt/gcp/load_balancer_source_ranges
      property: load-balancer-source-ranges
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sourcegraph-site-json
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
spec:
  backendType: vault
  vaultRole: sourcegraph
  data:
    - name: site.json
      key: kv/data/mgmt/sourcegraph/config
      property: site.json
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sourcegraph-extsvc-json
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
spec:
  backendType: vault
  vaultRole: sourcegraph
  data:
    - name: extsvc.json
      key: kv/data/mgmt/sourcegraph/config
      property: extsvc.json
